### ISSUE TITLE
Target does not exit

### ISSUE THREAD

**Issue by Bobowonnell** [Taguar258/Raven-Storm#20]
I know this is a duplicate but this is for a public ip address so I don't know what to do 
**Describe the bug**
Target does not exit
**To Reproduce**
>> set port 3074

   Port: 3074

>> set threads 100

   Number of Threads: 100

>> set ip 71.211.152.188

   Ip: 71.211.152.188

>> method

Method: UDP

>> UDP

      No such command.

>> set sleep 0.1

   Time in Seconds: 0.1

Error

>> set sleep .1

   Time in Seconds: .1

Error

>> set sleep

   Time in Seconds:  1

>> outtxt

disabled

>> run

Target does not exit.

**Expected behavior**
Successful attack started on my friends ip address
**Screenshots**

**OS:**
Windows

**Additional context**

**Comment by Taguar258** [comment]
Thank you Bobowonnell,
(I am sorry for answering this late.)
I edited the code right now to skip the issue your faceing.
You can now redownload Raven-Storm and try again, if it doesn't work then it most likely won't be an issue by Raven-Storm itself, rather an issue of the DOS method.

By the way, I consider to rewrite Raven-Storm and might get to this thread again soon.

Taguar

**Comment by Taguar258** [comment]
I will close this issue because I decided to archive this project, because I do not feel like updating it anymore.
I hope the issue you are facing is fixed by now.
