### ISSUE TITLE
i need help installing!

### ISSUE THREAD

**Issue by sonnysmith01** [Taguar258/Raven-Storm#22]
hello sir/miss,
i am trying to install your recommended program and i can not install it, i am on a windows 10 laptop that i just installed python v 3.9 and i dont know what to do to install it. i have typed nothing on python so it is fresh. Please may you walk my through step by step.

**Comment by Taguar258** [comment]
Hello sonysmith01,
I will try my best to explain it to you:
You will first need to download the latest version: `https://github.com/Taguar258/Raven-Storm/archive/master.zip`
After that you will need to navigate to the downloaded zip file, unzip it and open a new windows command prompt as administrator in the directory Raven-Storm.
You might be able to do so by pressing shift + left clicking on the folder and then selecting open in Powershell (Administrator).
In the command prompt you will have to type `pip install -r requirements.txt` and `python main.py`.
Just let me know, which step I should explain in more detail.

**Comment by Taguar258** [comment]
I will close this conservation due to inactivity.
