### ISSUE TITLE
need help w install

### ISSUE THREAD

**Issue by Fusiray** [Taguar258/Raven-Storm#23]
hi,
I need her w installing this thing on Mac OS 
I used terminal to run program
but on final stem when I type 'sudo rst'
it says 'sudo: rst: command not found'
what should I do?

**Comment by Taguar258** [comment]
Hello Fusiray,
May I ask how you installed it?
I'd suggest you to run it locally but cloning the repository and running main.py.
Though it should be possible to install it on MacOS/OSX.

**Comment by Taguar258** [comment]
I will close this issue due to inactivity.
