### ISSUE TITLE
bash: ./install_to_bin.sh: No such file or directory

### ISSUE THREAD

**Issue by httsmvkcom** [Taguar258/Raven-Storm#26]
![изображение](https://user-images.githubusercontent.com/51028674/102624419-0c573700-4155-11eb-8544-e3a2e9c11d4c.png)
Have to run it manually, the downloaded Raven-Storm folder does not contain this file

**Comment by Taguar258** [comment]
Hello httsmvkcom,
Thanks for submitting this issue.
To me it seems like it could not be fully downloaded and therefore the file was missing.
I don't know the reason though retrying might solve it.
